apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman-dev
  name: pacman-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman-dev
  template:
    metadata:
      labels:
        name: pacman-dev
    spec:
      containers:
      - image: localhost:5000/erbium/rum_pacman-nodejs-app:latest
        name: pacman-dev
        #imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080
          name: http-server
        env:
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4317"
            - name: OTEL_SERVICE_NAME
              value: "pacman-dev-svc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=pacman-dev"
            - name: SPLUNK_METRICS_ENABLED
              value: "true"
            - name: SPLUNK_DEBUG_METRICS_ENABLED
              value: "true"
            - name: SPLUNK_PROFILER_ENABLED
              value: "true"
            - name: SPLUNK_PROFILER_LOGS_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4317"
