apiVersion: v1
kind: Service
metadata:
  name: pacman-dev
  labels:
    name: pacman-dev
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8080
      protocol: TCP
  selector:
    name: pacman-dev
